#开启 SpringBoot 的 debug
#debug: true
spring:
  redis:
    host: f0t1.top
    port: 6379
    password:
    database: 0
    timeout: 0ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    url: jdbc:mysql://localhost:3306/gerry?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhou1990
  mvc:
    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static
  resources:
    add-mappings: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gerry.jnshu.pojo

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30

logging:
  level:
    root: info
    org.springframework.web: trace
    com.gerry.jnshu: info
  path: spring/log

